import AutoGenerated from "./components/core/overview/AutoGenerated";
import CumulativePL from "./components/core/overview/CumulativePL";
import DisciplineVsPerformance from "./components/core/overview/DisciplineVsPerformance";
import Metrics from "./components/core/overview/Metrics";
import NetDailyPL from "./components/core/overview/NetDailyPL";
import Overview from "./components/core/overview/Overview";
import SessionHealth from "./components/core/overview/SessionHealth";
import SessionStatus from "./components/core/overview/SessionStatus";
import TradeDistribution from "./components/core/overview/TradeDistribution";

export default function UserDashboard() {
  return (
    <>
      <SessionStatus />

      <div className="flex justify-center items-center gap-2">
        <CumulativePL />
        <NetDailyPL />
      </div>

      <Overview />

      <div className="flex justify-center items-center gap-2">
        <SessionHealth />
        <DisciplineVsPerformance />
      </div>

      <Metrics />

      <div className="flex justify-center items-center gap-2">
        <TradeDistribution />
        <AutoGenerated />
      </div>
    </>
  );
}
