// "use client";

// import { useFilters } from "@/contexts/FilterContext";
// import { useGetAllOverviewQuery } from "@/redux/features/overview/overviewApi";
// import { useRouter } from "next/navigation";
// import { useEffect } from "react";
// import AutoGenerated from "./components/core/overview/AutoGenerated";
// import CumulativePL from "./components/core/overview/CumulativePL";
// import DisciplineVsPerformance from "./components/core/overview/DisciplineVsPerformance";
// import Metrics from "./components/core/overview/Metrics";
// import NetDailyPL from "./components/core/overview/NetDailyPL";
// import Overview from "./components/core/overview/Overview";
// import SessionHealth from "./components/core/overview/SessionHealth";
// import SessionStatus from "./components/core/overview/SessionStatus";
// import TradeDistribution from "./components/core/overview/TradeDistribution";
// import TradingCalendar from "./components/core/overview/TradingCalendar";

// export default function UserDashboard() {
//   const router = useRouter();
//   const { filters } = useFilters();

//   useEffect(() => {
//     const token = localStorage.getItem("token");
//     if (!token) {
//       router.push("/login");
//     }
//   }, [router]);

//   const { data, isLoading, error, refetch } = useGetAllOverviewQuery(filters);

//   // Refetch when filters change
//   useEffect(() => {
//     refetch();
//   }, [filters, refetch]);

//   console.log(data);

//   if (isLoading) {
//     return (
//       <div className="min-h-screen bg-gray-50 dark:bg-gray-900 flex items-center justify-center">
//         <div className="text-center">
//           <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
//           <p className="mt-4 text-gray-600 dark:text-gray-400">
//             Loading dashboard...
//           </p>
//         </div>
//       </div>
//     );
//   }

//   if (error) {
//     return (
//       <div className="min-h-screen bg-gray-50 dark:bg-gray-900 flex items-center justify-center">
//         <div className="text-center">
//           <p className="text-red-600 dark:text-red-400">
//             Failed to load dashboard data. Please try again.
//           </p>
//         </div>
//       </div>
//     );
//   }

//   return (
//     <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
//       <div className="w-full mx-auto">
//         <div className="space-y-6 sm:space-y-8">
//           <SessionStatus sessionHealth={data?.sessionHealth} />

//           <Overview overviewData={data} />

//           <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 sm:gap-6">
//             <CumulativePL chartData={data?.chartData} />
//             <NetDailyPL chartData={data?.chartData} />
//           </div>

//           <div className="grid grid-cols-1 lg:grid-cols-[30%_69%] gap-4">
//             <SessionHealth sessionHealth={data?.sessionHealth} />
//             <DisciplineVsPerformance
//               disciplineData={data?.disciplineVsPerformance}
//             />
//           </div>

//           <Metrics exclusiveMetrics={data?.exclusiveMetrics} />

//           <div className="grid grid-cols-1 lg:grid-cols-[30%_69%] gap-4 sm:gap-6">
//             <TradeDistribution />
//             <AutoGenerated />
//           </div>

//           <TradingCalendar />
//         </div>
//       </div>
//     </div>
//   );
// }

"use client";

import { useFilters } from "@/contexts/FilterContext";
import { useGetAllOverviewQuery } from "@/redux/features/overview/overviewApi";
import { useEffect } from "react";
import AutoGenerated from "./components/core/overview/AutoGenerated";
import CumulativePL from "./components/core/overview/CumulativePL";
import DisciplineVsPerformance from "./components/core/overview/DisciplineVsPerformance";
import Metrics from "./components/core/overview/Metrics";
import NetDailyPL from "./components/core/overview/NetDailyPL";
import Overview from "./components/core/overview/Overview";
import SessionHealth from "./components/core/overview/SessionHealth";
import SessionStatus from "./components/core/overview/SessionStatus";
import TradeDistribution from "./components/core/overview/TradeDistribution";
import TradingCalendar from "./components/core/overview/TradingCalendar";

export default function UserDashboard() {
  const { filters } = useFilters();
  const { data, isLoading, error, refetch } = useGetAllOverviewQuery(filters);

  // No manual token check needed — middleware handles auth guard

  useEffect(() => {
    refetch();
  }, [filters, refetch]);

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-4 text-gray-600 dark:text-gray-400">
            Loading dashboard...
          </p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 flex items-center justify-center">
        <div className="text-center">
          <p className="text-red-600 dark:text-red-400">
            Failed to load dashboard data. Please try again.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="w-full mx-auto">
        <div className="space-y-6 sm:space-y-8">
          <SessionStatus sessionHealth={data?.sessionHealth} />
          <Overview overviewData={data} />
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 sm:gap-6">
            <CumulativePL chartData={data?.chartData} />
            <NetDailyPL chartData={data?.chartData} />
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-[30%_69%] gap-4">
            <SessionHealth sessionHealth={data?.sessionHealth} />
            <DisciplineVsPerformance
              disciplineData={data?.disciplineVsPerformance}
            />
          </div>
          <Metrics exclusiveMetrics={data?.exclusiveMetrics} />
          <div className="grid grid-cols-1 lg:grid-cols-[30%_69%] gap-4 sm:gap-6">
            <TradeDistribution />
            <AutoGenerated />
          </div>
          <TradingCalendar />
        </div>
      </div>
    </div>
  );
}
