import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navbar";
import ThemeProvider from "@/Providers/ThemeProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const times_raleway = localFont({
//   src: "./../fonts/Raleway-VariableFont_wght.ttf",
//   variable: "--times-new-roman",
//   weight: "100 400",
// });
// const times_raleway_bold = localFont({
//   src: "./../fonts/Raleway-VariableFont_wght.ttf",
//   variable: "--times-new-roman-bold",
//   weight: "500 900",
// });

// ${times_raleway.className} ${times_raleway_bold.variable} ==> use in className

export const metadata: Metadata = {
  title: "Bits Of Trade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <ThemeProvider>
            <Navbar />
            <>{children}</>
            <Footer />
          </ThemeProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
